name: Build & Run Test

on:
  push:
    paths:
      - '**.cpp'
      - '**.cs'
      - '.github/workflows/test.yml'
    branches:
    - "singleton"
  
  
    
  workflow_dispatch:
  
jobs:
  LinuxRun:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    
    - name: Install DotNet v6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.x'
        
    - name: Run
      run: |
        cd NiTiS.VE.Console/
        dotnet run -c Release
      
  WindowsRun:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    
    - name: Install DotNet v6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.x'
        
    - name: Run
      run: |
        cd NiTiS.VE.Console/
        dotnet run -c Release  
